import { KnowledgeGraphData } from "./knowledge-graph";

// Mock knowledge graph data per patient — mirrors LadybugDB schema:
// Entity(text STRING, label STRING) and RELATION(predicate, proposed_by, patient_acceptance)

export const MOCK_PATIENT_GRAPHS: Record<string, KnowledgeGraphData> = {
  // Sarah Mitchell — Anxiety, Work Stress, Self-Esteem
  "1": {
    entities: [
      { text: "Sarah", label: "PERSON" },
      { text: "Anxiety", label: "EMOTION" },
      { text: "Work Stress", label: "TRIGGER" },
      { text: "Self-Esteem", label: "THEME" },
      { text: "Rumination", label: "BEHAVIOR" },
      { text: "Catastrophizing", label: "BEHAVIOR" },
      { text: "Grounding Techniques", label: "STRATEGY" },
      { text: "Breathing Exercise", label: "STRATEGY" },
      { text: "Manager Meeting", label: "EVENT" },
      { text: "Fight-or-Flight", label: "CONCEPT" },
      { text: "Racing Heart", label: "SYMPTOM" },
      { text: "Sweaty Palms", label: "SYMPTOM" },
      { text: "Insomnia", label: "SYMPTOM" },
      { text: "Window of Tolerance", label: "CONCEPT" },
      { text: "Cognitive Restructuring", label: "STRATEGY" },
      { text: "Childhood Experiences", label: "EVENT" },
      { text: "Reduce Anxiety", label: "GOAL" },
      { text: "Build Confidence", label: "GOAL" },
    ],
    relations: [
      { source: "Sarah", target: "Anxiety", predicate: "experiences", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Work Stress", target: "Anxiety", predicate: "triggers", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Anxiety", target: "Rumination", predicate: "leads_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Anxiety", target: "Catastrophizing", predicate: "manifests_as", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Grounding Techniques", target: "Anxiety", predicate: "mitigates", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Manager Meeting", target: "Fight-or-Flight", predicate: "triggered", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Fight-or-Flight", target: "Racing Heart", predicate: "causes", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Fight-or-Flight", target: "Sweaty Palms", predicate: "causes", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Anxiety", target: "Insomnia", predicate: "causes", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Breathing Exercise", target: "Anxiety", predicate: "reduces", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Window of Tolerance", target: "Grounding Techniques", predicate: "expanded_by", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Self-Esteem", target: "Childhood Experiences", predicate: "linked_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Cognitive Restructuring", target: "Catastrophizing", predicate: "addresses", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Sarah", target: "Reduce Anxiety", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Sarah", target: "Build Confidence", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Self-Esteem", target: "Build Confidence", predicate: "related_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Rumination", target: "Insomnia", predicate: "worsens", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Work Stress", target: "Manager Meeting", predicate: "includes", proposed_by: "patient", patient_acceptance: "accepted" },
    ],
  },

  // James Rivera — Grief, Family Dynamics, Coping
  "2": {
    entities: [
      { text: "James", label: "PERSON" },
      { text: "Grief", label: "EMOTION" },
      { text: "Family Dynamics", label: "THEME" },
      { text: "Coping", label: "THEME" },
      { text: "Anger", label: "EMOTION" },
      { text: "Denial", label: "BEHAVIOR" },
      { text: "Loss of Father", label: "EVENT" },
      { text: "Isolation", label: "BEHAVIOR" },
      { text: "Journaling", label: "STRATEGY" },
      { text: "Boundary Setting", label: "STRATEGY" },
      { text: "Mother", label: "PERSON" },
      { text: "Accept Loss", label: "GOAL" },
      { text: "Sadness", label: "EMOTION" },
    ],
    relations: [
      { source: "James", target: "Grief", predicate: "experiences", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Loss of Father", target: "Grief", predicate: "caused", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Grief", target: "Anger", predicate: "manifests_as", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Grief", target: "Denial", predicate: "manifests_as", proposed_by: "practitioner", patient_acceptance: "rejected" },
      { source: "Grief", target: "Sadness", predicate: "includes", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Family Dynamics", target: "Mother", predicate: "involves", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Mother", target: "Boundary Setting", predicate: "requires", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Isolation", target: "Grief", predicate: "worsened_by", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Journaling", target: "Coping", predicate: "supports", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "James", target: "Accept Loss", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
    ],
  },

  // Amara Chen — PTSD, Relationships, Resilience
  "3": {
    entities: [
      { text: "Amara", label: "PERSON" },
      { text: "PTSD", label: "THEME" },
      { text: "Relationships", label: "THEME" },
      { text: "Resilience", label: "CONCEPT" },
      { text: "Hypervigilance", label: "SYMPTOM" },
      { text: "Flashbacks", label: "SYMPTOM" },
      { text: "Nightmares", label: "SYMPTOM" },
      { text: "EMDR", label: "STRATEGY" },
      { text: "Traumatic Event", label: "EVENT" },
      { text: "Avoidance", label: "BEHAVIOR" },
      { text: "Trust Issues", label: "BEHAVIOR" },
      { text: "Attachment Style", label: "CONCEPT" },
      { text: "Safety Planning", label: "STRATEGY" },
      { text: "Narrative Therapy", label: "STRATEGY" },
      { text: "Partner", label: "PERSON" },
      { text: "Dissociation", label: "SYMPTOM" },
      { text: "Self-Compassion", label: "CONCEPT" },
      { text: "Grounding", label: "STRATEGY" },
      { text: "Feel Safe", label: "GOAL" },
      { text: "Healthy Relationships", label: "GOAL" },
      { text: "Emotional Regulation", label: "CONCEPT" },
    ],
    relations: [
      { source: "Amara", target: "PTSD", predicate: "diagnosed_with", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Traumatic Event", target: "PTSD", predicate: "caused", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "PTSD", target: "Hypervigilance", predicate: "causes", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "PTSD", target: "Flashbacks", predicate: "causes", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "PTSD", target: "Nightmares", predicate: "causes", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "PTSD", target: "Dissociation", predicate: "causes", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "EMDR", target: "Flashbacks", predicate: "targets", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "EMDR", target: "Traumatic Event", predicate: "processes", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Avoidance", target: "Relationships", predicate: "disrupts", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Trust Issues", target: "Attachment Style", predicate: "rooted_in", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Safety Planning", target: "PTSD", predicate: "manages", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Narrative Therapy", target: "Resilience", predicate: "builds", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Amara", target: "Partner", predicate: "in_relationship_with", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Partner", target: "Trust Issues", predicate: "affected_by", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Self-Compassion", target: "Resilience", predicate: "contributes_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Grounding", target: "Dissociation", predicate: "counteracts", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Amara", target: "Feel Safe", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Amara", target: "Healthy Relationships", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Emotional Regulation", target: "PTSD", predicate: "helps_manage", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Hypervigilance", target: "Relationships", predicate: "strains", proposed_by: "practitioner", patient_acceptance: "accepted" },
    ],
  },

  // David Okafor — Depression, Isolation, Sleep
  "4": {
    entities: [
      { text: "David", label: "PERSON" },
      { text: "Depression", label: "EMOTION" },
      { text: "Isolation", label: "BEHAVIOR" },
      { text: "Sleep Issues", label: "SYMPTOM" },
      { text: "Fatigue", label: "SYMPTOM" },
      { text: "Low Motivation", label: "SYMPTOM" },
      { text: "Behavioral Activation", label: "STRATEGY" },
      { text: "Sleep Hygiene", label: "STRATEGY" },
      { text: "Retirement", label: "EVENT" },
      { text: "Loss of Purpose", label: "THEME" },
      { text: "Find Meaning", label: "GOAL" },
    ],
    relations: [
      { source: "David", target: "Depression", predicate: "experiences", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Depression", target: "Isolation", predicate: "leads_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Depression", target: "Sleep Issues", predicate: "causes", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Depression", target: "Fatigue", predicate: "causes", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Depression", target: "Low Motivation", predicate: "causes", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Behavioral Activation", target: "Low Motivation", predicate: "addresses", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Sleep Hygiene", target: "Sleep Issues", predicate: "improves", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Retirement", target: "Loss of Purpose", predicate: "triggered", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Loss of Purpose", target: "Depression", predicate: "contributes_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "David", target: "Find Meaning", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Isolation", target: "Depression", predicate: "worsens", proposed_by: "practitioner", patient_acceptance: "accepted" },
    ],
  },

  // Elena Vasquez — Identity, Career, Mindfulness
  "5": {
    entities: [
      { text: "Elena", label: "PERSON" },
      { text: "Identity", label: "THEME" },
      { text: "Career Uncertainty", label: "TRIGGER" },
      { text: "Mindfulness", label: "STRATEGY" },
      { text: "Imposter Syndrome", label: "CONCEPT" },
      { text: "Values Clarification", label: "STRATEGY" },
      { text: "Self-Discovery", label: "GOAL" },
      { text: "Anxiety", label: "EMOTION" },
      { text: "Perfectionism", label: "BEHAVIOR" },
      { text: "Journaling", label: "STRATEGY" },
      { text: "Cultural Identity", label: "THEME" },
      { text: "Family Expectations", label: "TRIGGER" },
      { text: "Body Scan", label: "STRATEGY" },
      { text: "Authenticity", label: "CONCEPT" },
    ],
    relations: [
      { source: "Elena", target: "Identity", predicate: "exploring", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Career Uncertainty", target: "Anxiety", predicate: "triggers", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Imposter Syndrome", target: "Career Uncertainty", predicate: "amplifies", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Mindfulness", target: "Anxiety", predicate: "reduces", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Values Clarification", target: "Identity", predicate: "supports", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Perfectionism", target: "Imposter Syndrome", predicate: "feeds", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Cultural Identity", target: "Identity", predicate: "part_of", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Family Expectations", target: "Career Uncertainty", predicate: "contributes_to", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Journaling", target: "Self-Discovery", predicate: "supports", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Body Scan", target: "Mindfulness", predicate: "technique_of", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Elena", target: "Self-Discovery", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Authenticity", target: "Identity", predicate: "goal_of", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Family Expectations", target: "Cultural Identity", predicate: "shapes", proposed_by: "patient", patient_acceptance: "accepted" },
    ],
  },

  // Marcus Webb — Anger, Communication, Boundaries
  "6": {
    entities: [
      { text: "Marcus", label: "PERSON" },
      { text: "Anger", label: "EMOTION" },
      { text: "Communication", label: "THEME" },
      { text: "Boundaries", label: "CONCEPT" },
      { text: "DBT Skills", label: "STRATEGY" },
      { text: "Assertiveness", label: "STRATEGY" },
      { text: "Frustration", label: "EMOTION" },
      { text: "Workplace Conflict", label: "EVENT" },
      { text: "Partner Conflict", label: "EVENT" },
      { text: "Emotional Flooding", label: "CONCEPT" },
      { text: "Distress Tolerance", label: "STRATEGY" },
      { text: "Passive-Aggressive", label: "BEHAVIOR" },
      { text: "Cognitive Rehearsal", label: "STRATEGY" },
      { text: "Healthy Expression", label: "GOAL" },
      { text: "Childhood Anger", label: "EVENT" },
      { text: "Role Play", label: "STRATEGY" },
    ],
    relations: [
      { source: "Marcus", target: "Anger", predicate: "struggles_with", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Workplace Conflict", target: "Anger", predicate: "triggers", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Partner Conflict", target: "Frustration", predicate: "triggers", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Anger", target: "Emotional Flooding", predicate: "leads_to", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "DBT Skills", target: "Emotional Flooding", predicate: "manages", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Distress Tolerance", target: "Anger", predicate: "reduces", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Communication", target: "Assertiveness", predicate: "improved_by", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Passive-Aggressive", target: "Communication", predicate: "hinders", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Boundaries", target: "Partner Conflict", predicate: "resolves", proposed_by: "practitioner", patient_acceptance: "pending" },
      { source: "Cognitive Rehearsal", target: "Assertiveness", predicate: "practices", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Role Play", target: "Boundaries", predicate: "practices", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Childhood Anger", target: "Anger", predicate: "root_of", proposed_by: "practitioner", patient_acceptance: "accepted" },
      { source: "Marcus", target: "Healthy Expression", predicate: "wants", proposed_by: "patient", patient_acceptance: "accepted" },
      { source: "Frustration", target: "Passive-Aggressive", predicate: "manifests_as", proposed_by: "practitioner", patient_acceptance: "accepted" },
    ],
  },
};

// Fallback: generate an empty graph for unknown patients
export function getPatientGraph(patientId: string): KnowledgeGraphData {
  return MOCK_PATIENT_GRAPHS[patientId] || { entities: [], relations: [] };
}
